on:
  pull_request:
  workflow_dispatch:

name: pkgdown-pr

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      PKGDOWN_DEV_MODE: devel
      R_KEEP_PKG_SOURCE: yes
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: build pkgdown reference index
        run: pkgdown::build_reference_index()
        shell: Rscript {0}

      - name: build pkgdown articles
        run: pkgdown::build_articles()
        shell: Rscript {0}
